# Generated by Django 5.2.9 on 2026-04-03 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='mountain', help_text='Например: mountain, waves, flame', max_length=50, verbose_name='Иконка (Lucide)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активности',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_per_night', models.PositiveIntegerField(verbose_name='Цена за сутки (руб)')),
                ('guests_count', models.PositiveSmallIntegerField(default=4, verbose_name='Кол-во гостей')),
                ('bedrooms', models.PositiveSmallIntegerField(default=1, verbose_name='Спальни')),
                ('beds', models.PositiveSmallIntegerField(default=2, verbose_name='Кровати')),
                ('bathrooms', models.PositiveSmallIntegerField(default=1, verbose_name='Санузлы')),
                ('amenities', models.TextField(blank=True, help_text='Каждое удобство с новой строки', verbose_name='Удобства')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+7 (999) 123-45-67', max_length=20, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('address', models.CharField(default='КЧР, Урупский район, п. Азиатский', max_length=255, verbose_name='Адрес')),
                ('hero_title', models.CharField(default='Отдых в горах Кавказа', max_length=200, verbose_name='Заголовок Hero')),
                ('hero_subtitle', models.TextField(default='Уютные дома в живописном поселке Азиатский у реки Большая Лаба', verbose_name='Подзаголовок Hero')),
                ('about_title', models.CharField(default='Поселок Азиатский', max_length=200, verbose_name='Заголовок "О поселке"')),
                ('about_text', models.TextField(default='', verbose_name='Текст "О поселке"')),
                ('yandex_map_embed', models.TextField(blank=True, verbose_name='Код карты Яндекс (iframe)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('guests', models.PositiveSmallIntegerField(default=1, verbose_name='Кол-во гостей')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='houses/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Фото дома',
                'verbose_name_plural': 'Фото домов',
                'ordering': ['order'],
            },
        ),
    ]
