# Generated by Django 5.2.9 on 2026-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_galleryimage_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDivider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('after_houses', 'После блока Дома'), ('after_about', 'После блока О поселке'), ('after_gallery', 'После блока Галерея')], max_length=20, unique=True, verbose_name='Позиция')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('icon', models.CharField(default='mountain', max_length=50, verbose_name='Иконка (Lucide)')),
                ('image', models.ImageField(upload_to='dividers/', verbose_name='Фоновое фото')),
            ],
            options={
                'verbose_name': 'Фото-разделитель',
                'verbose_name_plural': 'Фото-разделители',
            },
        ),
    ]
