# Generated by Django 5.2.9 on 2026-04-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sectiondivider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondivider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dividers/', verbose_name='Фоновое фото'),
        ),
    ]
