# Generated by Django 5.2.9 on 2026-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sectiondivider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('distance_km', models.PositiveIntegerField(verbose_name='Расстояние (км)')),
                ('drive_time', models.CharField(help_text='Например: 5 ч 30 мин', max_length=50, verbose_name='Время в пути')),
                ('description', models.TextField(blank=True, help_text='Через какие города, качество дороги и тд', verbose_name='Описание маршрута')),
                ('lat', models.FloatField(help_text='Для построения маршрута в Яндекс.Картах', verbose_name='Широта города')),
                ('lon', models.FloatField(help_text='Для построения маршрута в Яндекс.Картах', verbose_name='Долгота города')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Маршрут из города',
                'verbose_name_plural': 'Как добраться',
                'ordering': ['order'],
            },
        ),
    ]
