# Generated by Django 5.2.9 on 2026-04-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_routecity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Итого (руб)'),
        ),
        migrations.AddField(
            model_name='house',
            name='weekend_price',
            field=models.PositiveIntegerField(blank=True, help_text='Если пусто — используется будничная цена', null=True, verbose_name='Цена за сутки выходные (руб)'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price_per_night',
            field=models.PositiveIntegerField(verbose_name='Цена за сутки будни (руб)'),
        ),
        migrations.CreateModel(
            name='HolidaySurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Новый год 2026, Майские', max_length=100, verbose_name='Название')),
                ('date_from', models.DateField(verbose_name='Дата начала')),
                ('date_to', models.DateField(verbose_name='Дата окончания')),
                ('price_override', models.PositiveIntegerField(blank=True, help_text='Абсолютная цена за сутки', null=True, verbose_name='Фиксированная цена (руб)')),
                ('percentage_markup', models.PositiveSmallIntegerField(blank=True, help_text='Например: 30 для +30% к базовой цене', null=True, verbose_name='Наценка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Чем выше — тем приоритетнее при пересечении', verbose_name='Приоритет')),
                ('house', models.ForeignKey(blank=True, help_text='Пусто = для всех домов', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Ценовая наценка',
                'verbose_name_plural': 'Ценовые наценки',
                'ordering': ['-order'],
            },
        ),
    ]
