# Generated by Django 5.1.7 on 2026-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_bookingrequest_is_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото "О поселке" 1'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото "О поселке" 2'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото "О поселке" 3'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Фото "О поселке" 4'),
        ),
    ]
